name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - []
body:
  - type: markdown
    attributes:
      value: |
        ## Note that clairvoyancy does not exist ... no details to replicate = no response
  - type: checkboxes
    id: checked-docu
    attributes:
      label: Own Analysis
      description: You have read the documentation which did not provide help [Documentation](https://github.com/vingerha/gtfs2/wiki/6.-Issues,-challenges-&-workarounds). 
      options:
        - label: I cannot find my issue in the documentation
          required: true
  - type: checkboxes
    id: checked-docu
    attributes:
      label: Own Analysis
      description: Is you static data file up-to-date, this may change every month 
      options:
        - label: My static data (zip) is up to date
          required: true          
  - type: textarea
    id: what-happened
    attributes:
      label: A clear and concise description of what the bug is.
      description: |
        - has it worked before
        - what it does not do vs. expectation
        - have you verified if the source/provider is working correctly, usually they have their own website.
      render: shell
    validations:
      required: true  
  - type: textarea
    id: sources
    attributes:
      label: Provide details on the data source(s)
      description: |
        - url to the zip file of the **static datasource**
        - have you updated the datasource to the latest version, some of them update on a weekly basis
        - if (!) realtime issue of if(!) position issue: url to its source
      render: shell
    validations:
      required: true        
  - type: textarea
    id: startstop_based
    attributes:
      label: Config in case of setup using start / stop station
      description: |
        - route ID
        - stop ID
        - outward/return
      render: shell
  - type: textarea
    id: location_based
    attributes:
      label: Config in case of setup using location based departures
      description: |
        - location lat/lon used
        - which transport types are missing or incorrect
      render: shell  
  - type: textarea
    id: release
    attributes:
      label: Info on your installed version
      description: |
        - gtfs2 release 
        - HA type (HAOS/Container)
    validations:
      required: true  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell



